### ISSUE TITLE
odML install via pip not working

### ISSUE THREAD

**Issue by hendrikrth** [G-Node/python-odml#159]
I tried to install odML via pip on several machines (Mac, CentOs) and with several python versions (2.7, 3.6), and also with miniconda. Installation always goes through, but when I try to follow the tutorial and load the file 

```python
import odml

file_to_load = '/home/hendrik/VirtualEnvs/odml_py2/opt/local/python-odml/doc/example_odMLs/THGTTG.odml'

odmlEx = odml.load(file_to_load)
```
it gives me the following error message:
AttributeError: 'module' object has no attribute 'load'.

But when I install odML, by cloning the repo and running `python setup.py install`, everything is fine and I can load the file. This is really a problem for me, I just wanted to let you know.

**Comment by achilleas-k** [comment]
Thanks for letting us know. The version on PyPI now is 1.3.1, which has a few changes, most importantly that the GUI is not included.
The tutorial hasn't been updated yet, though the load function should be returning in the next proper release, which is why it works when you clone and build master.

For now, the easiest way to get the old version and keep using it like you did is to force pip to install 1.2.1: `pip install odml==1.2.1`

Sorry for the inconvenience.

**Comment by hendrikrth** [comment]
Thanks for your fast reply, ...
I tried your approach but I still get the same error message. Therefore I wanted to check if this problem might arise from my OS setup. I installed a clean Ubuntu (Ubuntu 16.04.3 LTS) in a VirtualBox and then installed odml-1.2.1. But I still get the same error. 

Still I believe this isn't much of a problem, because I can just use the manual installation via `git clone ...` and `python setup.py install` which is fine for me.

Best wishes, Hendrik

**Comment by achilleas-k** [comment]
This should be fixed now. A new version (1.3.2) has been uploaded to PyPI which exposes the save and load functions to the top level module. Could you test it and let me know if it works OK for you?

**Comment by hendrikrth** [comment]
So I updated odML to version 1.3.2 and the load and save function are now visible. But when I run my example script again, I am getting the following error messages:
```python
(odml_py2) Hendriks-MacBook-Pro:VirtualEnv hendrikrothe$ python test.py 
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    d = odml.load(to_load)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/fileio.py", line 8, in load
    return reader.from_file(filename)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/odmlparser.py", line 264, in from_file
    odml_doc = xmlparser.XMLReader().fromFile(file)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 162, in fromFile
    return self.parse_element(root)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 198, in parse_element
    return getattr(self, "parse_" + node.tag)(node, self.tags[node.tag])
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 272, in parse_odML
    doc = self.parse_tag(root, fmt)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 229, in parse_tag
    sub_obj = self.parse_element(node)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 198, in parse_element
    return getattr(self, "parse_" + node.tag)(node, self.tags[node.tag])
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 288, in parse_section
    return self.parse_tag(root, fmt, create=lambda **kargs: fmt.create(name))
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 229, in parse_tag
    sub_obj = self.parse_element(node)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 198, in parse_element
    return getattr(self, "parse_" + node.tag)(node, self.tags[node.tag])
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 288, in parse_section
    return self.parse_tag(root, fmt, create=lambda **kargs: fmt.create(name))
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 229, in parse_tag
    sub_obj = self.parse_element(node)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 198, in parse_element
    return getattr(self, "parse_" + node.tag)(node, self.tags[node.tag])
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 292, in parse_property
    return self.parse_tag(root, fmt, insert_children=False, create=create)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 226, in parse_tag
    self.is_valid_argument(node.tag, fmt, root, node)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 178, in is_valid_argument
    self.error("Invalid element <%s> inside <%s> tag" % (tag_name, parent_node.tag), parent_node if child is None else child)
  File "/Users/hendrikrothe/VirtualEnv/odml_py2/lib/python2.7/site-packages/odml/tools/xmlparser.py", line 185, in error
    raise ParserException(msg)
odml.tools.xmlparser.ParserException: Invalid element <type> inside <property> tag (line 13)
```

This error doesn't show up when using the master branch.

**Comment by jgrewe** [comment]
Hi @hendrikrth, sorry for the delay, we are all on vacation at the moment. To me it looks like the file you are reading was created according to the data model used in the master development branch (version 1.1, should be noted as attribute in the top-level "odml" tag). 
The error you got, however, is not really helpful in that sense. Thanks for pointing that out! Would you mind trying one of the example files in the version_1.3/docs folder? They should work.

**Comment by mpsonntag** [comment]
Closing due to resolving of the initial issue and inactivity on the unrelated follow up conversation.
