### ISSUE TITLE
RDFWriter breaks on unknown output format

### ISSUE THREAD

**Issue by mpsonntag** [G-Node/python-odml#215]
The RDFWriter breaks on an unsupported RDF format with an obscure error message. Provide a more userfriendly error message.

**Comment by rickskyy** [comment]
Are you pointing out about this kind of traceback?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rdflib/plugin.py", line 100, in get
    p = _plugins[(name, kind)]
KeyError: ('wrong_format', <class 'rdflib.serializer.Serializer'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  .......
  File "/usr/local/lib/python3.5/dist-packages/rdflib/graph.py", line 940, in serialize
    serializer = plugin.get(format, Serializer)(self)
  File "/usr/local/lib/python3.5/dist-packages/rdflib/plugin.py", line 103, in get
    "No plugin registered for (%s, %s)" % (name, kind))
rdflib.plugin.PluginException: No plugin registered for (wrong_format, <class 'rdflib.serializer.Serializer'>)
```
