### ISSUE TITLE
unicode issue under py3

### ISSUE THREAD

**Issue by jpresern** [G-Node/python-odml#44]
Got an exception thrown under py3.5. 

Template chosen: continuous_recording_template.xml
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "/home/janez/python_projects/odml/python-odml/odml/terminology.py", line 69, in _load
    fp = cache_load(url)
  File "/home/janez/python_projects/odml/python-odml/odml/terminology.py", line 25, in cache_load
    filename = md5(url).hexdigest() + '.' + os.path.basename(url)
TypeError: Unicode-objects must be encoded before hashing

maybe:
filename = md5(url.encode("utf-8")).hexdigest() + "." + os.path.basename(url) ??

**Comment by jgrewe** [comment]
thanks for reporting, this issue should be fixed
